<a href="https://colab.research.google.com/github/MAGB21/homrigaAlgorithm/blob/main/hormiga.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

la homria debe encontrar comida

In [32]:
import numpy as np
import random

In [33]:
filas=10
columnas=10
habitacion = np.zeros((filas, columnas))
print(habitacion)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [34]:
comida_x = random.randint(0, 9)  # Genera un número entre 1 y 10 (ambos inclusive)
comida_y = random.randint(0, 9)  # Genera un número entre 1 y 10 (ambos inclusive)
habitacion[comida_x ,comida_y]=2
print(habitacion)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
hormiga_x = random.randint(0, 9)  # Genera un número entre 1 y 10 (ambos inclusive)
hormiga_y = random.randint(0, 9)  # Genera un número entre 1 y 10 (ambos inclusive)
habitacion[hormiga_x ,hormiga_y ]=4
print(habitacion)
print(hormiga_x)
print(hormiga_y)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
4
0


In [36]:
#MOVIMIENTOS IZQUIERDA(I) ADELANTE(A) DERECHA(D) QUIETO(Q)
#EJEMPLO DE INDIVIDUO1 HORMIGA=[A,A,D,D,A,I,Q,Q,Q,Q]
#EJEMPLO DE INDIVIDUO2 HORMIGA=[D,D,A,I,A,D,Q,Q,Q,Q]
#GENERAR LA VARIABLE EJE CON LOS SIGUIENTES VALORES NORTE(0)-ESTE(1)-SUR(2)-OESTE(3)

In [37]:
#VERIFICA A QUE EJES TIENE PERMITIDO LA HORMIGA MOVERSE
def elegirEje(hormiga_x,hormiga_y):
  eje = [0,1,2,3]#EJE VALORES NORTE(0)-ESTE(1)-SUR(2)-OESTE(3)
  if hormiga_x == 0:
      eje.remove(0)
  elif hormiga_x == 9:
      eje.remove(2)
  if hormiga_y == 0:
      eje.remove(3)
  elif hormiga_y == 9:
      eje.remove(1)
  ejeElegido = random.choice(eje)
  #print("eje elegido de funcion elegirEje", ejeElegido)
  return ejeElegido

In [38]:
#ROTA A LA HORMIGA DEPENDIENDO DEL MOVIMIENTO QUE SE HAGA(IZQUIERDA O DERECHA)
def rotarEje(ejeElegido,direccion):
  #MOVIMIENTO A LA DERECHA
  #print("entro rotarEje y eje ya contenido ",ejeElegido)
  if ejeElegido == 0 and direccion == 'D':#NORTE
    ejeElegido =1
  elif ejeElegido == 1 and direccion == 'D':#OESTE
    ejeElegido =2
  elif ejeElegido == 2 and direccion == 'D':#SUR
    ejeElegido =3
  elif ejeElegido == 3 and direccion == 'D':#ESTE
    ejeElegido =0
    #MOVIMIENTO A LA IZQUIERDA
  elif ejeElegido == 0 and direccion == 'I':#NORTE
    ejeElegido = 3
  elif ejeElegido == 1 and direccion == 'I':#OESTE
    ejeElegido = 0
  elif ejeElegido == 2 and direccion == 'I':#SUR
    ejeElegido = 1
  elif ejeElegido == 3 and direccion == 'I':#ESTE
    ejeElegido = 2
  #print("eje elegido de funcion rotarEje", ejeElegido)
  return ejeElegido


In [39]:
#definir funcion para calcular la distancia
def calDist(hormiga_x,hormiga_y,comida_x,comida_y):
    distancia=abs(hormiga_x-comida_x)+abs(hormiga_y-comida_y)
    #retornara la distancias hechas por los distintos patrones de movimiento de la hormiga
    return distancia


In [42]:
#GENERA VARIOS MOVIMIENTOS PARA LA HORMIGA
def generarMovimientos():
  movimientos=['A','D','I','Q']
  numOportunidades=10
  hormiga=[]
  for i in range(numOportunidades):
    movHormiga=[]
    for j in range(numOportunidades):
      movHormiga.append(random.choice(movimientos))
    hormiga.append(movHormiga)
  return hormiga

In [43]:
def modificarCord(hormiga_x,hormiga_y):
  ejeElegido=elegirEje(hormiga_x,hormiga_y)
  if ejeElegido == 0:
      hormiga_x -=1
      #print("resta X")
  elif ejeElegido == 1:
      hormiga_y +=1
      #print("suma Y")
  elif ejeElegido == 2:
      hormiga_x +=1
      #print("suma X")
  elif  ejeElegido  == 3:
      hormiga_y -=1
      #print("resta Y")
  return hormiga_x,hormiga_y

In [44]:
#PROGRAMA PRINCIPAL
#VARIABLES
ID=1
disAndMov= dict()
ejeElegido= elegirEje(hormiga_x,hormiga_y)
movimientos=generarMovimientos()
for movInHormiga in movimientos:
  for i in movInHormiga:
    if i == 'A':
      habitacion[hormiga_x ,hormiga_y ]=0
      hormiga_x,hormiga_y=modificarCord(hormiga_x,hormiga_y)
      #print("valores ACTUALES DE X", hormiga_x," & Y", hormiga_y)
      habitacion[hormiga_x ,hormiga_y ]=4
    if i == 'D':
      ejeElegido = rotarEje(ejeElegido,'D')
    if i == 'I':
      ejeElegido = rotarEje(ejeElegido,'I')
  disAndMov[f"distancia {ID}"]=calDist(hormiga_x,hormiga_y,comida_x,comida_y)
  disAndMov[f"movHormiga {ID}"]=movInHormiga
  ID+=1

#calcular distancias
# if hormiga_x == comida_x and hormiga_y == comida_y:
#   print("COMIDA ENCONTRADA")
#   habitacion[hormiga_x ,hormiga_y ]=0
#   habitacion[comida_x ,comida_y ]=4
#   comidaEcontrada=False
print(habitacion)
print(disAndMov)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
{'distancia 1': 3, 'movHormiga 1': ['Q', 'Q', 'Q', 'Q', 'I', 'Q', 'D', 'I', 'D', 'A'], 'distancia 2': 3, 'movHormiga 2': ['I', 'D', 'Q', 'Q', 'I', 'I', 'I', 'Q', 'I', 'D'], 'distancia 3': 3, 'movHormiga 3': ['I', 'I', 'D', 'D', 'D', 'D', 'D', 'D', 'D', 'Q'], 'distancia 4': 3, 'movHormiga 4': ['D', 'A', 'Q', 'A', 'Q', 'A', 'D', 'A', 'I', 'Q'], 'distancia 5': 2, 'movHormiga 5': ['D', 'D', 'I', 'Q', 'I', 'Q', 'A', 'A', 'A', 'D'], 'distancia 6': 3, 'movHormiga 6': ['A', 'I', 'Q', 'D', 'D', 'Q', 'A', 'Q', 'D', 'A'], 'distancia 7': 6, 'movHormiga 7': ['A', 'I', 'I', 'A', 'I', 'D', 'D', 'A', 'A', 'A'], 'distancia 8': 5, 'movHormiga 8': ['A', 'D', 'A', 'I', 'Q', 'Q', '