<a href="https://colab.research.google.com/github/MAGB21/homrigaAlgorithm/blob/main/hormiga.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

la homria debe encontrar comida

In [ ]:
filas=10
columnas=10
import numpy as np
habitacion = np.zeros((filas, columnas))
print(habitacion)

In [ ]:
import random
comida_x = random.randint(0, 9)  # Genera un número entre 1 y 10 (ambos inclusive)
comida_y = random.randint(0, 9)  # Genera un número entre 1 y 10 (ambos inclusive)
habitacion[comida_x ,comida_y]=2
print(habitacion)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
hormiga_x = random.randint(0, 9)  # Genera un número entre 1 y 10 (ambos inclusive)
hormiga_y = random.randint(0, 9)  # Genera un número entre 1 y 10 (ambos inclusive)
habitacion[hormiga_x ,hormiga_y ]=4
print(habitacion)
print(hormiga_x)
print(hormiga_y)

In [ ]:
#MOVIMIENTOS IZQUIERDA(I) ADELANTE(A) DERECHA(D) QUIETO(Q)
#EJEMPLO DE INDIVIDUO1 HORMIGA=[A,A,D,D,A,I,Q,Q,Q,Q]
#EJEMPLO DE INDIVIDUO2 HORMIGA=[D,D,A,I,A,D,Q,Q,Q,Q]
#GENERAR LA VARIABLE EJE CON LOS SIGUIENTES VALORES NORTE(0)-ESTE(1)-SUR(2)-OESTE(3)

In [ ]:
#VERIFICA A QUE EJES TIENE PERMITIDO LA HORMIGA MOVERSE
def elegirEje(hormiga_x,hormiga_y):
  eje = [0,1,2,3]#EJE VALORES NORTE(0)-ESTE(1)-SUR(2)-OESTE(3)
  if hormiga_x == 0:
      eje.remove(0)
  elif hormiga_x == 9:
      eje.remove(2)
  if hormiga_y == 0:
      eje.remove(3)
  elif hormiga_y == 9:
      eje.remove(1)
  ejeElegido = random.choice(eje)
  print("eje elegido de funcion elegirEje", ejeElegido)
  return ejeElegido

In [ ]:
#ROTA A LA HORMIGA DEPENDIENDO DEL MOVIMIENTO QUE SE HAGA(IZQUIERDA O DERECHA)
def rotarEje(ejeElegido,direccion):
  #MOVIMIENTO A LA DERECHA
  print("entro rotarEje y eje ya contenido ",ejeElegido)
  if ejeElegido == 0 and direccion == 'D':#NORTE
    ejeElegido =1
  elif ejeElegido == 1 and direccion == 'D':#OESTE
    ejeElegido =2
  elif ejeElegido == 2 and direccion == 'D':#SUR
    ejeElegido =3
  elif ejeElegido == 3 and direccion == 'D':#ESTE
    ejeElegido =0
    #MOVIMIENTO A LA IZQUIERDA
  elif ejeElegido == 0 and direccion == 'I':#NORTE
    ejeElegido = 3
  elif ejeElegido == 1 and direccion == 'I':#OESTE
    ejeElegido = 0
  elif ejeElegido == 2 and direccion == 'I':#SUR
    ejeElegido = 1
  elif ejeElegido == 3 and direccion == 'I':#ESTE
    ejeElegido = 2
  print("eje elegido de funcion rotarEje", ejeElegido)
  return ejeElegido


In [ ]:
#definir funcion para calcular la distancia
def calDist(hormiga_x,hormiga_y,comida_x,comida_y):
    distancia=abs(hormiga_x-comida_x)+abs(hormiga_y-comida_y)
    #retornara la distancias hechas por los distintos patrones de movimiento de la hormiga
    return distancia


In [ ]:
def fitness():
  pass

In [ ]:
#GENERA VARIOS MOVIMIENTOS PARA LA HORMIGA
def generarMovimientos():
  movimientos=['A','D','I','Q']
  numOportunidades=10
  hormiga=[]
  for i in range(numOportunidades):
    movHormiga=[]
    for j in range(numOportunidades):
      movHormiga.append(random.choice(movimientos))
    hormiga.append(movHormiga)

['I', 'Q', 'D', 'A', 'Q', 'D', 'I', 'A', 'D', 'Q']


In [ ]:
def modificarCord(hormiga_x,hormiga_y, ejeElegido):
  if ejeElegido == 0:
      hormiga_x -=1
      print("resta X")
  elif ejeElegido == 1:
      hormiga_y +=1
      print("suma Y")
  elif ejeElegido == 2:
      hormiga_x +=1
      print("suma X")
  elif  ejeElegido  == 3:
      hormiga_y -=1
      print("resta Y")
  return hormiga_x,hormiga_y

In [ ]:

#PROGRAMA PRINCIPAL
comidaEcontrada=True
ejeElegido= elegirEje(hormiga_x,hormiga_y)
for e in ant_t:
  if e == 'A':
    habitacion[hormiga_x ,hormiga_y ]=0
    hormiga_x,hormiga_y=modificarCord(hormiga_x,hormiga_y,ejeElegido)
    print("valores ACTUALES DE X", hormiga_x," & Y", hormiga_y)
    habitacion[hormiga_x ,hormiga_y ]=4
  if e == 'D':
    ejeElegido = rotarEje(ejeElegido,'D')
  if e == 'I':
    ejeElegido = rotarEje(ejeElegido,'I')
calDist(hormiga_x,comida_x,hormiga_y,comida_y)#calcular distancias
if hormiga_x == comida_x and hormiga_y == comida_y:
  print("COMIDA ENCONTRADA")
  habitacion[hormiga_x ,hormiga_y ]=0
  habitacion[comida_x ,comida_y ]=4
  comidaEcontrada=False
print(habitacion)